"""The fleet, one engine in detail, its work order, and the policy comparison."""

from __future__ import annotations

import pandas as pd
import streamlit as st

from copilot import charts, config, models, shared, simulator, theme, workorder


def body(predictions: pd.DataFrame, simulation: pd.DataFrame, metrics: dict, llm_model: str) -> None:
    snapshot = shared.fleet_snapshot(predictions)
    sensors = metrics["sensors_used"]

    st.subheader("Fleet")
    counts = snapshot["tier"].value_counts()
    cols = st.columns(4)
    for col, tier in zip(cols, ("Red", "Amber", "Green")):
        col.metric(f"{theme.TIER_MARK[tier]} {tier}", int(counts.get(tier, 0)))
    cols[3].metric("Engines", len(snapshot))

    table = pd.DataFrame(
        {
            "cycle": snapshot["cycle"],
            "predicted RUL": snapshot["point"].round(1),
            "interval": [f"{lo:.0f} to {hi:.0f}" for lo, hi in zip(snapshot["lower"], snapshot["upper"])],
            "tier": snapshot["tier"],
            "top driver": snapshot["driver1"],
            "true RUL": snapshot["true_rul"],
        }
    ).sort_values("predicted RUL")

    left, right = st.columns([3, 2])
    left.dataframe(
        table.style.map(lambda t: f"color: {theme.TIER_COLOURS[t]}; font-weight: 600", subset=["tier"]),
        height=360,
    )
    right.plotly_chart(charts.rul_histogram(snapshot), use_container_width=True)

    st.divider()
    st.subheader("Engine detail and replay")
    engine = st.selectbox("Engine", options=sorted(predictions["unit"].unique()),
                          index=int(table.index[0]) - 1 if len(table) else 0)
    history = predictions[predictions["unit"] == engine].reset_index(drop=True)
    cycle = st.slider(
        "Replay cycle", int(history["cycle"].min()), int(history["cycle"].max()),
        int(history["cycle"].max()),
        help="Step the engine forward and watch the prediction and tier update",
    )
    row = history[history["cycle"] == cycle].iloc[0]

    metric_cols = st.columns(4)
    metric_cols[0].metric("Predicted RUL", f"{row['point']:.0f} cycles")
    metric_cols[1].metric("Interval", f"{row['lower']:.0f} to {row['upper']:.0f}")
    metric_cols[2].metric("Tier", f"{theme.TIER_MARK[row['tier']]} {row['tier']}")
    metric_cols[3].metric("True RUL", f"{row['true_rul']:.0f} cycles")

    st.plotly_chart(charts.prediction_history(history, cycle), use_container_width=True)
    st.plotly_chart(charts.attribution_chart(row), use_container_width=True)

    driver_sensors = list(dict.fromkeys(models.sensor_of(row[f"driver{i}"]) for i in (1, 2, 3)))
    for col, sensor in zip(st.columns(len(driver_sensors)), driver_sensors):
        col.plotly_chart(charts.sensor_trend(history, sensor, cycle), use_container_width=True)

    st.divider()
    st.subheader("Work order")
    st.caption(f"Generated by {llm_model}. The prediction is fixed input: the model explains it, never changes it.")
    if st.button("Generate work order", type="primary"):
        with st.spinner("Writing work order"):
            try:
                generated = workorder.generate(row, sensors, history, model=llm_model)
            except Exception as error:  # surfaced, never swallowed
                st.error(f"{type(error).__name__}: {error}")
                return
        st.session_state["work_order"] = generated

    if st.session_state.get("work_order") is not None:
        render_work_order(st.session_state["work_order"])

    st.divider()
    st.subheader("Policy simulator")
    assumptions = shared.assumption_form()
    st.caption(
        f"Replays {simulation['unit'].nunique()} engines with complete run-to-failure trajectories, using "
        "out-of-fold predictions so no engine is scored by a model that trained on it. The truncated test "
        "engines cannot be used here: most stop recording while still healthy, long before any pull decision."
    )
    results = simulator.simulate(simulation, assumptions)
    curve = simulator.sensitivity(simulation, assumptions)
    left, right = st.columns(2)
    left.plotly_chart(charts.policy_chart(results), use_container_width=True)
    right.plotly_chart(charts.sensitivity_chart(curve, assumptions.predictive_threshold), use_container_width=True)
    st.dataframe(
        results.assign(
            total_cost=results["total_cost"].map("${:,.0f}".format),
            downtime_days=results["downtime_days"].map("{:,.0f}".format),
            wasted_cycles=results["wasted_cycles"].map("{:,.0f}".format),
        )
    )


def render_work_order(generated: workorder.Generated) -> None:
    order = generated.work_order
    if generated.grounded:
        st.success("Groundedness check passed: every cited sensor value matches the data")
    else:
        st.error("Groundedness check failed: " + "; ".join(generated.failures))

    head = st.columns(4)
    head[0].metric("Priority", order.priority)
    head[1].metric("Subsystem", order.suspected_subsystem)
    head[2].metric("Predicted RUL", f"{order.predicted_rul} cycles")
    head[3].metric("Interval", f"{order.interval.low} to {order.interval.high}")

    left, right = st.columns(2)
    left.markdown("**Evidence**")
    left.dataframe(pd.DataFrame([e.model_dump() for e in order.evidence]), hide_index=True)
    right.markdown("**Recommended actions**")
    right.markdown("\n".join(f"1. {a}" for a in order.recommended_actions))
    if order.parts_to_stage:
        right.markdown("**Parts to stage**")
        right.markdown("\n".join(f"- {p}" for p in order.parts_to_stage))

    st.markdown(f"**Justification.** {order.justification}")
    st.markdown(f"**Confidence.** {order.confidence_note}")
    st.caption(
        f"{generated.latency_s:.1f} s, {generated.input_tokens} in / {generated.output_tokens} out, "
        f"${generated.cost_usd:.4f}"
    )
    with st.expander("Raw JSON"):
        st.json(order.model_dump())
