"""Diagnosis: one engine, its evidence, and the work order that comes out of it."""

from __future__ import annotations

import anthropic
import pandas as pd
import streamlit as st

from copilot import charts, data, shared, theme, workorder
from copilot.views import card


def body(predictions: pd.DataFrame, metrics: dict, llm_model: str, llm_effort: str) -> None:
    sensors = metrics["sensors_used"]
    snapshot = shared.fleet_snapshot(predictions).sort_values("point")

    engine = st.selectbox(
        "Engine",
        options=[int(unit) for unit in snapshot.index],
        key="selected_engine",
        help="Ordered by predicted remaining life, most urgent first",
    )
    history = predictions[predictions["unit"] == engine].reset_index(drop=True)
    cycle = st.slider(
        "Replay cycle",
        int(history["cycle"].min()),
        int(history["cycle"].max()),
        int(history["cycle"].max()),
        key=f"replay_cycle_{engine}",
        help="Step the engine forward and watch the prediction and tier update",
    )
    row = history[history["cycle"] == cycle].iloc[0]

    metric_cols = st.columns(4)
    metric_cols[0].metric("Predicted RUL", f"{row['point']:.0f} cycles")
    metric_cols[1].metric("Interval", f"{row['lower']:.0f} to {row['upper']:.0f}")
    metric_cols[2].metric("Tier", f"{theme.TIER_MARK[row['tier']]} {row['tier']}")
    metric_cols[3].metric("True RUL", f"{row['true_rul']:.0f} cycles", help="Held-out label, shown for comparison")

    st.plotly_chart(charts.prediction_history(history, cycle), use_container_width=True)
    st.plotly_chart(charts.attribution_chart(row), use_container_width=True)

    driver_sensors = list(dict.fromkeys(data.sensor_of(row[f"driver{i}"]) for i in (1, 2, 3)))
    for col, sensor in zip(st.columns(len(driver_sensors)), driver_sensors):
        col.plotly_chart(charts.sensor_trend(history, sensor, cycle), use_container_width=True)

    st.divider()
    st.subheader("Work order")
    st.caption(f"Generated by {llm_model} at {llm_effort} effort. The prediction is fixed input: "
               "the model explains it, never changes it.")
    if st.button("Generate work order", type="primary", key="generate_work_order"):
        with st.spinner("Writing work order"):
            try:
                generated = workorder.generate(row, sensors, history, model=llm_model, effort=llm_effort)
            except anthropic.AuthenticationError:
                st.error(
                    "The API rejected the key. Check ANTHROPIC_API_KEY, then restart Streamlit: "
                    "the environment is read once at startup, so editing your shell profile does "
                    "not reach a running app."
                )
                return
            except Exception as error:  # surfaced, never swallowed
                st.error(f"{type(error).__name__}: {error}")
                return
        st.session_state["work_order"] = generated

    generated = st.session_state.get("work_order")
    if generated is not None:
        card.render_full(
            generated.work_order, row, history, generated.checks,
            footer=f"{generated.model} at {generated.effort or 'default'} effort | "
                   f"{generated.latency_s:.1f} s | {generated.input_tokens} in / "
                   f"{generated.output_tokens} out | ${generated.cost_usd:.4f}",
        )
