"""Diagnosis: one engine, its evidence, and the work order that comes out of it."""

from __future__ import annotations

import pandas as pd
import streamlit as st

from copilot import charts, data, shared, theme, workorder


def body(predictions: pd.DataFrame, metrics: dict, llm_model: str) -> None:
    sensors = metrics["sensors_used"]
    snapshot = shared.fleet_snapshot(predictions).sort_values("point")

    engine = st.selectbox(
        "Engine",
        options=[int(unit) for unit in snapshot.index],
        key="selected_engine",
        help="Ordered by predicted remaining life, most urgent first",
    )
    history = predictions[predictions["unit"] == engine].reset_index(drop=True)
    cycle = st.slider(
        "Replay cycle",
        int(history["cycle"].min()),
        int(history["cycle"].max()),
        int(history["cycle"].max()),
        key=f"replay_cycle_{engine}",
        help="Step the engine forward and watch the prediction and tier update",
    )
    row = history[history["cycle"] == cycle].iloc[0]

    metric_cols = st.columns(4)
    metric_cols[0].metric("Predicted RUL", f"{row['point']:.0f} cycles")
    metric_cols[1].metric("Interval", f"{row['lower']:.0f} to {row['upper']:.0f}")
    metric_cols[2].metric("Tier", f"{theme.TIER_MARK[row['tier']]} {row['tier']}")
    metric_cols[3].metric("True RUL", f"{row['true_rul']:.0f} cycles", help="Held-out label, shown for comparison")

    st.plotly_chart(charts.prediction_history(history, cycle), use_container_width=True)
    st.plotly_chart(charts.attribution_chart(row), use_container_width=True)

    driver_sensors = list(dict.fromkeys(data.sensor_of(row[f"driver{i}"]) for i in (1, 2, 3)))
    for col, sensor in zip(st.columns(len(driver_sensors)), driver_sensors):
        col.plotly_chart(charts.sensor_trend(history, sensor, cycle), use_container_width=True)

    st.divider()
    st.subheader("Work order")
    st.caption(f"Generated by {llm_model}. The prediction is fixed input: the model explains it, never changes it.")
    if st.button("Generate work order", type="primary", key="generate_work_order"):
        with st.spinner("Writing work order"):
            try:
                generated = workorder.generate(row, sensors, history, model=llm_model)
            except Exception as error:  # surfaced, never swallowed
                st.error(f"{type(error).__name__}: {error}")
                return
        st.session_state["work_order"] = generated

    if st.session_state.get("work_order") is not None:
        render_work_order(st.session_state["work_order"])


def render_work_order(generated: workorder.Generated) -> None:
    order = generated.work_order
    if generated.grounded:
        st.success("Groundedness check passed: every cited sensor value matches the data")
    else:
        st.error("Groundedness check failed: " + "; ".join(generated.failures))

    head = st.columns(4)
    head[0].metric("Priority", order.priority)
    head[1].metric("Subsystem", order.suspected_subsystem)
    head[2].metric("Predicted RUL", f"{order.predicted_rul} cycles")
    head[3].metric("Interval", f"{order.interval.low} to {order.interval.high}")

    left, right = st.columns(2)
    left.markdown("**Evidence**")
    left.dataframe(pd.DataFrame([e.model_dump() for e in order.evidence]), hide_index=True)
    right.markdown("**Recommended actions**")
    right.markdown("\n".join(f"1. {a}" for a in order.recommended_actions))
    if order.parts_to_stage:
        right.markdown("**Parts to stage**")
        right.markdown("\n".join(f"- {p}" for p in order.parts_to_stage))

    st.markdown(f"**Justification.** {order.justification}")
    st.markdown(f"**Confidence.** {order.confidence_note}")
    st.caption(
        f"{generated.latency_s:.1f} s, {generated.input_tokens} in / {generated.output_tokens} out, "
        f"${generated.cost_usd:.4f}"
    )
    with st.expander("Raw JSON"):
        st.json(order.model_dump())
